version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: pomodoro_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "8080:3306" 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: pomodoro_app
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      # these env names match what your index.js already reads
      HOST_DB: db
      USER_DB: ${MYSQL_USER}
      PASSWORD_DB: ${MYSQL_PASSWORD}
      DATABASE_DB: ${MYSQL_DATABASE}
      SECRET_SESSION: ${SECRET_SESSION}
      PORT: ${PORT:-3000}
    # For local dev hot-reload, you can add volumes & change command to use nodemon (optional)
    # volumes:
    #   - ./:/usr/src/app
    #   - /usr/src/app/node_modules
    # command: sh /usr/local/bin/wait-for-db.sh
volumes:
  db_data:
